### ISSUE TITLE
AttributeError: 'PTuneForLAMA' object has no attribute 'prompt'

### ISSUE THREAD

**Issue by puraminy** [THUDM/P-tuning#16]
I called 

`python cli.py --model_name=gpt2`

After several epochs, it printed the following error:

P1001 Dev Epoch 41 Loss: 0.007320404052734375 Hit@1: 0.6756756756756757
Traceback (most recent call last):
  File "cli.py", line 238, in <module>
    main()
  File "cli.py", line 234, in main
    trainer.train()
  File "cli.py", line 197, in train
    self.save(best_ckpt)
  File "cli.py", line 171, in save
    print("# Prompt:", self.model.prompt)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", 
line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'PTuneForLAMA' object has no attribute 'prompt'

**Comment by aaafc** [comment]
Yes, I've encountered the problem myself, yet I'm still looking for the reason.
I've used GPT-2 as my PLM as well, and after 46 epochs, the same error occurs at line "cli.py, line 171" in the script.
Though I'm not sure why this is taken place, it appears that one can simply comment out that line, and the script still works.
