### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute '_get_node_flag'

### ISSUE THREAD

**Issue by YCC-324** [THUDM/P-tuning#44]
Hello, which version of "fairseq" and "omegaconf" did you use? I meet the following error.

Traceback (most recent call last):
  File "cli.py", line 238, in <module>
    main()
  File "cli.py", line 233, in main
    trainer = Trainer(args)
  File "cli.py", line 109, in __init__
    self.model = PTuneForLAMA(args, self.device, self.args.template)
  File "/home/yuec/P-tuning/LAMA/p_tuning/modeling.py", line 33, in __init__
    self.model = create_model(self.args)
  File "/home/yuec/P-tuning/LAMA/p_tuning/models.py", line 8, in create_model
    return load_megatron_lm(args)
  File "/home/yuec/P-tuning/LAMA/megatron_11b/megatron_wrapper.py", line 31, in load_megatron_lm
    distributed_utils.infer_init_method(task_args)
  File "/home/yuec/miniconda3/envs/run_self_learning/lib/python3.7/site-packages/fairseq/distributed/utils.py", line 70, in infer_init_method
    with open_dict(cfg):
  File "/home/yuec/miniconda3/envs/run_self_learning/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/yuec/miniconda3/envs/run_self_learning/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 943, in open_dict
    prev_state = config._get_node_flag("struct")
AttributeError: 'Namespace' object has no attribute '_get_node_flag'

**Comment by jeremy313** [comment]
Did you solve it? I have the same issue. My faireseq==0.12.2 and omegaonf==2.0.6
